export const Users = [
    {
      id:1,
      profilePicture: "Screenshots/1.jpg",
      username: "Safak Kocaoglu",
    },
    {
      id:2,
      profilePicture: "Screenshots/2.jpg",
      username: "Mohammad",
    },
    {
      id:3,
      profilePicture: "Screenshots/3.jpg",
      username: "Shiraazi",
    },
    {
      id:4,
      profilePicture: "Screenshots/4.jpg",
      username: "Sai",
    },
    {
      id:5,
      profilePicture: "Screenshots/5.jpg",
      username: "Thomas Holden",
    },
    {
      id:6,
      profilePicture: "Screenshots/6.jpg",
      username: "Sahakar",
    },
    {
      id:7,
      profilePicture: "Screenshots/7.jpg",
      username: "Doland Trump",
    },
    {
      id:8,
      profilePicture: "Screenshots/8.jpg",
      username: "Modi Bhau",
    },
    {
      id:9,
      profilePicture: "Screenshots/9.jpg",
      username: "Pappu Gandhi",
    },
    {
      id:10,
      profilePicture: "Screenshots/10.jpg",
      username: "Twitter Tillu",
    },
  ];
  
  export const Posts = [
    {
      id: 1,
      desc: "Love For All, Hatred For None.",
      photo: "Screenshots/11.jpg",
      date: "5 mins ago",
      userId: 1,
      like: 32,
      comment: 9,
    },
    {
      id: 2,
      photo: "Screenshots/2.jpg",
      date: "15 mins ago",
      userId: 2,
      like: 2,
      comment: 1,
    },
    {
      id: 3,
      desc: "Every moment is a fresh beginning.",
      photo: "Screenshots/8.jpg",
      date: "1 hour ago",
      userId: 3,
      like: 61,
      comment: 2,
    },
    {
      id: 4,
      photo: "Screenshots/10.jpg",
      date: "4 hours ago",
      userId: 4,
      like: 7,
      comment: 3,
    },
    {
      id: 5,
      photo: "Screenshots/5.jpg",
      date: "5 hours ago",
      userId: 5,
      like: 23,
      comment: 5,
    },
    {
      id: 6,
      photo: "Screenshots/9.jpg",
      date: "1 day ago",
      userId: 6,
      like: 44,
      comment: 6,
    },
    {
      id: 7,
      desc: "Never regret anything that made you smile.",
      photo: "Screenshots/7.jpg",
      date: "2 days ago",
      userId: 7,
      like: 52,
      comment: 3,
    },
    {
      id: 8,
      photo: "Screenshots/8.jpg",
      date: "3 days ago",
      userId: 8,
      like: 15,
      comment: 1,
    },
    {
      id: 9,
      desc: "Change the world by being yourself.",
      photo: "Screenshots/1.jpg",
      date: "5 days ago",
      userId: 9,
      like: 11,
      comment: 2,
    },
    {
      id: 10,
      photo: "Screenshots/12.jpg",
      date: "1 week ago",
      userId: 10,
      like: 104,
      comment: 12,
    },
  ];